analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    # STYLE
    - camel_case_types
    - camel_case_extensions
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - directives_ordering
    - curly_braces_in_flow_control_structures

    # DOCUMENTATION
    - slash_for_doc_comments
    - package_api_docs # prefer
    - public_member_api_docs # prefer

    # USAGE
    - implementation_imports
    - avoid_relative_lib_imports # prefer
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings # prefer
    - unnecessary_brace_in_string_interps # avoid
    - prefer_collection_literals
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - prefer_equal_for_default_values
    - avoid_init_to_null
    - unnecessary_getters_setters
    - unnecessary_this
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - avoid_catching_errors
    - use_rethrow_when_possible

    # DESIGN
    - use_to_and_as_if_applicable # prefer
    - prefer_mixin
    - prefer_final_fields # prefer
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_null # avoid
    - avoid_returning_this # avoid
    - type_annotate_public_apis # prefer
    - avoid_return_types_on_setters # avoid
    - prefer_generic_function_type_aliases
    - avoid_private_typedef_functions # prefer
    - hash_and_equals
    - avoid_null_checks_in_equality_operators

    #PEDANTIC
    - avoid_empty_else
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - empty_catches
    - no_duplicate_case_values
    - null_closures
    - prefer_contains
    - prefer_is_empty
    - prefer_is_not_empty
    - recursive_getters
    - unawaited_futures
    - unnecessary_null_in_if_null_operators
    - unrelated_type_equality_checks
    - valid_regexps

    #FLUTTER
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - package_names
    - package_prefixed_library_names
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements